### ISSUE TITLE
Typo Layot -> Layout

### ISSUE THREAD

**Issue by Ganneff** [AntonGepting/tmux-interface-rs#10]
https://github.com/AntonGepting/tmux-interface-rs/blob/7a1dea0ad658e2cb8743311480d207ad1d196a48/src/commands/windows_and_panes/select_layout.rs#L39

Hi

guess that should be SelectLayout there and wherever else this struct is used.

Ganneff

**Comment by AntonGepting** [comment]
Hi,

changed, added in `hotfix`, will be added in `main` with next version.

Thank you for reporting!

**Comment by AntonGepting** [comment]
fixed in [v0.3.0](https://github.com/AntonGepting/tmux-interface-rs/tree/v0.3.0)

thank you, and sorry for long delay
