### ISSUE TITLE
Order of option matters?! Shouldn't, imo.

### ISSUE THREAD

**Issue by Ganneff** [AntonGepting/tmux-interface-rs#11]
Hi,

with the following code snippet:
```rust
let foo = TmuxCommand::new()
             .select_layout()
             .target_pane("vm_dmz:1")
             .layout_name("tiled")
             .output()?;
println!("{foo:#?}");
```

If one puts the .layout_name *before* the .target_pane, foo will contain a tmux error like
_stderr: "usage: select-layout [-Enop] [-t target-pane] [layout-name]\n",_

The above order (first target_pane, then layout_name) works nicely.

Appears that the order of them function calls translates directly into the order things take on commandline for tmux.

I think that **shouldn't** be the case, unless the options really interact with each other. A user of this interface usually shouldn't need to care of the order tmux expects things in, that **IMO** would be the interfaces job to handle.

Greetings,
  Ganneff

**Comment by AntonGepting** [comment]
Hi,

thank you for your improvement idea. I agree, for an end user it would be better to have suggested abstraction and safety. 

Most likely it can be changed right along with planned direct/control mode, single/multiple commands features. They imply some rework of basic instances. Anyway unfortunately I can't promise any dates.
