### ISSUE TITLE
How to send keys to your tmux session with this project?

### ISSUE THREAD

**Issue by SpiderUnderUrBed** [AntonGepting/tmux-interface-rs#19]
Hi, I am curious, is this possible? To send key input to your tmux screen via this project.

**Comment by AntonGepting** [comment]
Hi,

since the commands part of the library is just a wrapper around the tmux CLI, you can just use the corresponding functions (e.g. the `send_keys` function for the `send-keys` tmux command)

Example
```
...

// tmux send-keys abc
Tmux::new()
    .add_command(SendKeys::new().key("abc"))
    .output()
    .unwrap();
...
```
